use_default_settings: true

general:
  debug: false
  instance_name: Jose's SearXNG

search:
  safe_search: 1
  autocomplete: "duckduckgo"
  formats:
    - html
    - json

server:
  secret_key: "REDACTED_CHANGE_ME"
  limiter: false
  image_proxy: true
